name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build mod
      run: make -j$(nproc)

    - name: Upload jars
      uses: actions/upload-artifact@v2
      with:
        name: Desktop and Universal builds
        path: |
          BetaMindy-Desktop.jar#
          BetaMindy.jar