name: Java CI with Gradle

on:
  push:
    branches: [ master, erekir ]
  pull_request:
    branches: [ master, erekir ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: build-tools
      run: sdkmanager "build-tools;29.0.3"
    - name: Add Android SDK to PATH
      run: echo "${ANDROID_HOME}/build-tools/29.0.3" >> $GITHUB_PATH

    - name: Grant execute permissions
      run: |
        chmod +x gradlew
        chmod +x alpha-bleed
        chmod +x alpha-bleeding-linux.exe

    - name: Build with Gradle
      run: ./gradlew alphableed buildDex

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: betamindy in a box
        path: build/libs/[!raw-]*.jar
